# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceDetect', '0002_auto_20170618_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picturedata',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='picturedata',
            name='img2',
        ),
    ]
