# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceDetect', '0003_auto_20170702_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picturedata',
            name='data1',
        ),
        migrations.RemoveField(
            model_name='picturedata',
            name='data2',
        ),
        migrations.RemoveField(
            model_name='picturedata',
            name='password',
        ),
        migrations.RemoveField(
            model_name='picturedata',
            name='username',
        ),
    ]
